// SPDX-License-Identifier: MIT
// !! THIS FILE WAS AUTOGENERATED BY abi-to-sol v0.5.3. SEE SOURCE BELOW. !!
pragma solidity ^0.8.9;

import "./IExternalAdapterTxResponse.sol";
import "../types/ProtocolTypes.sol";

interface ISettlementEngine {
    event CrosschainSettlementRequested(
        address payer,
        address receiver,
        uint16 chainId,
        uint256 timestamp,
        string txHash,
        bytes32 requestId
    );
    event CrosschainSettlementRequestFulfilled(
        string payer,
        string receiver,
        uint16 chainId,
        uint256 amount,
        uint256 timestamp,
        string txHash,
        bytes32 settlementId
    );
    event ExternalAdapterAdded(address indexed adapter, bytes32 ccy);
    event ExternalAdapterUpdated(address indexed adapter, bytes32 ccy);

    function addExternalAdapter(address _adapter, bytes32 _ccy) external;

    function getExternalAdapters(bytes32) external view returns (address);

    function fulfillSettlementRequest(
        bytes32 _requestId,
        IExternalAdapterTxResponse.FulfillData calldata _txData,
        bytes32 _ccy
    ) external;

    function getVersion() external view returns (uint16);

    function replaceExternalAdapter(address _adapter, bytes32 _ccy) external;

    function getSettlementRequests(bytes32)
        external
        view
        returns (ProtocolTypes.SettlementRequest memory);

    function verifyPayment(
        address _counterparty,
        bytes32 _ccy,
        uint256 _payment,
        uint256 _timestamp,
        string calldata _txHash
    ) external payable returns (bytes32);
}
