name: 🐞 Bug Report
description: Report a bug or unexpected behavior in USDFC stablecoin contracts
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a potential bug in the USDFC stablecoin contracts! Please fill out the sections below.
  - type: input
    id: description
    attributes:
      label: Description
      description: What went wrong? Describe the bug in detail.
      placeholder: "e.g. mint() allows minting without collateral"
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Provide step-by-step instructions to reproduce the issue.
      placeholder: |
        1. Deploy on local Hardhat network  
        2. call mint() with zero collateral  
        3. observe unexpected behavior
  - type: input
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
  - type: input
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
  - type: input
    id: environment
    attributes:
      label: Environment
      description: Network, contract version, node, etc.
      placeholder: "e.g. v1.0.0, Hardhat, Node.js v18"
