name: 🐞 Bug Report
description: Report a bug or unexpected behavior in smart contracts
title: '[Bug]: '
labels: ['bug']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a potential bug in our smart contracts! Please fill out the sections below.
  - type: input
    id: description
    attributes:
      label: Description
      description: What went wrong? Describe the bug in detail.
      placeholder: 'e.g. Liquidator failed to liquidate undercollateralized position'
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Provide step-by-step instructions to reproduce the issue.
      placeholder: |
        1. Deploy on local Hardhat network  
        2. Create an order  
        3. Attempt to liquidate undercollateralized position
  - type: input
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: 'e.g. Liquidation should succeed'
  - type: input
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: 'e.g. Transaction reverted with custom error'
  - type: input
    id: environment
    attributes:
      label: Environment
      description: Network, contract version, node, etc.
      placeholder: 'e.g. v1.3.0, Hardhat, Node.js v18'
