name: Deploy

on:
  workflow_dispatch:
    inputs:
      network:
        description: 'Network'
        required: true
        default: 'development'
        type: choice
        options:
          - development
          - staging

jobs:
  test:
    name: Test on a Fork
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.network }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ (github.event.inputs.network == 'staging' && 'main') || 'develop' }}
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - name: Set environment variables
        run: |
          echo "UNISWAP_SWAP_ROUTER_CONTRACT=${{ vars.UNISWAP_SWAP_ROUTER_CONTRACT }}" >> $GITHUB_ENV
          echo "UNISWAP_SWAP_QUOTER_CONTRACT=${{ vars.UNISWAP_SWAP_QUOTER_CONTRACT }}" >> $GITHUB_ENV
          echo "TOKEN_EFIL=${{ vars.TOKEN_EFIL }}" >> $GITHUB_ENV
          echo "TOKEN_USDC=${{ vars.TOKEN_USDC }}" >> $GITHUB_ENV
          echo "TOKEN_WBTC=${{ vars.TOKEN_WBTC }}" >> $GITHUB_ENV
          echo "TOKEN_WETH=${{ vars.TOKEN_WETH }}" >> $GITHUB_ENV
          echo "FIL_TO_ETH_RATE=${{ vars.FIL_TO_ETH_RATE }}" >> $GITHUB_ENV
          echo "ETH_TO_USD_RATE=${{ vars.ETH_TO_USD_RATE }}" >> $GITHUB_ENV
          echo "BTC_TO_ETH_RATE=${{ vars.BTC_TO_ETH_RATE }}" >> $GITHUB_ENV
          echo "USDC_TO_ETH_RATE=${{ vars.USDC_TO_ETH_RATE }}" >> $GITHUB_ENV
          echo "PRIVATE_KEY=${{ secrets.PRIVATE_KEY }}" >> $GITHUB_ENV
          echo "ALCHEMY_API_KEY=${{ secrets.ALCHEMY_API_KEY }}" >> $GITHUB_ENV
          echo "TENDERLY_USER=${{ vars.TENDERLY_USER }}" >> $GITHUB_ENV
          echo "TENDERLY_PROJECT=${{ vars.TENDERLY_PROJECT }}" >> $GITHUB_ENV
          echo "TENDERLY_ACCESS_KEY=${{ secrets.TENDERLY_ACCESS_KEY }}" >> $GITHUB_ENV
      - name: Install Dependencies
        run: npm ci
      - name: Build Smart Contracts
        run: npm run compile
      - name: Create a fork environment
        run: |
          FORK_ID=$(npm run fork ${{ github.event.inputs.network }} | tail -n 1)
          echo "fork id is $FORK_ID"
          echo "FORK_ID=$FORK_ID" >> $GITHUB_ENV
      - name: Deploy for fork environment
        run: npm run deploy ${{ github.event.inputs.network }}
        env:
          FORK_RPC_ENDPOINT: https://rpc.tenderly.co/fork/${{ env.FORK_ID }}
      - name: Check diff
        shell: bash
        id: diff
        run: |
          echo "::set-output name=count::$(git diff --staged --name-only . | wc -l)"
      - name: Run a Loan Test on fork environment
        if: steps.diff.outputs.count > 0
        env:
          USE_DEFAULT_ACCOUNTS: true
          FORK_RPC_ENDPOINT: https://rpc.tenderly.co/fork/${{ env.FORK_ID }}
        run: npx hardhat --network ${{ github.event.inputs.network }} test "scripts/zc-e2e.ts" --bail
      - name: Delete the fork environment
        run: npm run unfork --forkid $FORK_ID
  deploy:
    name: Deploy Smart Contracts
    runs-on: ubuntu-latest
    if: ${{ !contains(needs.*.result, 'failure') && !contains(needs.*.result, 'canceled') }}
    environment: ${{ github.event.inputs.network }}
    needs: [test]
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.MACHINE_USER_APP_ID }}
          private_key: ${{ secrets.MACHINE_USER_PRIVATE_KEY }}
      - uses: actions/checkout@v3
        with:
          ref: ${{ (github.event.inputs.network == 'staging' && 'main') || 'develop' }}
          token: ${{ steps.generate_token.outputs.token }}
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - name: 'Setup for git'
        run: |
          git config user.name "SF Machine User[bot]"
          git config user.email "${{ secrets.MACHINE_USER_APP_ID }}+sf-machine-user[bot]@users.noreply.github.com"
      - name: Install Dependencies
        run: npm ci
      - name: Build Smart Contracts
        run: npm run compile
      - name: Set environment variables
        run: |
          echo "INITIAL_COMPOUND_FACTOR=${{ vars.INITIAL_COMPOUND_FACTOR }}" >> $GITHUB_ENV
          echo "MARKET_OBSERVATION_PERIOD=${{ vars.MARKET_OBSERVATION_PERIOD }}" >> $GITHUB_ENV
          echo "UNISWAP_SWAP_ROUTER_CONTRACT=${{ vars.UNISWAP_SWAP_ROUTER_CONTRACT }}" >> $GITHUB_ENV
          echo "UNISWAP_SWAP_QUOTER_CONTRACT=${{ vars.UNISWAP_SWAP_QUOTER_CONTRACT }}" >> $GITHUB_ENV
          echo "TOKEN_EFIL=${{ vars.TOKEN_EFIL }}" >> $GITHUB_ENV
          echo "TOKEN_USDC=${{ vars.TOKEN_USDC }}" >> $GITHUB_ENV
          echo "TOKEN_WBTC=${{ vars.TOKEN_WBTC }}" >> $GITHUB_ENV
          echo "TOKEN_WETH=${{ vars.TOKEN_WETH }}" >> $GITHUB_ENV
          echo "FIL_TO_ETH_RATE=${{ vars.FIL_TO_ETH_RATE }}" >> $GITHUB_ENV
          echo "ETH_TO_USD_RATE=${{ vars.ETH_TO_USD_RATE }}" >> $GITHUB_ENV
          echo "BTC_TO_ETH_RATE=${{ vars.BTC_TO_ETH_RATE }}" >> $GITHUB_ENV
          echo "USDC_TO_ETH_RATE=${{ vars.USDC_TO_ETH_RATE }}" >> $GITHUB_ENV
          echo "PRIVATE_KEY=${{ secrets.PRIVATE_KEY }}" >> $GITHUB_ENV
          echo "ALCHEMY_API_KEY=${{ secrets.ALCHEMY_API_KEY }}" >> $GITHUB_ENV
          echo "ENABLE_FAUCET=true" >> $GITHUB_ENV
      - name: Deploy smart contracts
        run: |
          npm run deploy ${{ github.event.inputs.network }}
          git add .
      - name: Check diff
        shell: bash
        id: deploymentDiff
        run: |
          echo "::set-output name=count::$(git diff --staged --name-only . | wc -l)"
      - name: Commit and push
        shell: bash
        if: steps.deploymentDiff.outputs.count > 0
        run: |
          git commit -m "chore: update smart contracts" --no-verify
          git push
      - name: Update documents
        if: ${{ github.event.inputs.network == 'development' }}
        run: |
          npm run docgen
          git add .
      - name: Check diff
        shell: bash
        id: docgenDiff
        run: |
          echo "::set-output name=count::$(git diff --staged --name-only . | wc -l)"
      - name: Commit and push
        shell: bash
        if: steps.docgenDiff.outputs.count > 0
        run: |
          git commit -m "chore: update docs" --no-verify
          git push
      - name: Merge main into develop
        shell: bash
        if: ${{ github.event.inputs.network == 'staging' }}
        run: |
          git switch develop
          git merge main
          git push
