name: Deploy Smart Contracts

on:
  # For testing
  # workflow_run:
  #   workflows: ['Test on a Fork']
  #   types: [completed]
  push:
    branches:
      - master
      - develop
      # For testing
      - SF-18-add-staging

jobs:
  deploy:
    name: Deploy Smart Contracts
    runs-on: ubuntu-latest
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.MACHINE_USER_APP_ID }}
          private_key: ${{ secrets.MACHINE_USER_PRIVATE_KEY }}
      - uses: actions/checkout@v3
        withL:
          token: ${{ steps.generate_token.outputs.token }}
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - name: Install Dependencies
        run: npm ci
      - name: Build Smart Contracts
        run: npm run compile
      - name: Deploy for development environment
        # For testing
        # if: ${{ github.ref == 'refs/heads/develop' }}
        if: ${{ github.ref == 'refs/heads/SF-18-add-staging' }}
        env:
          PRIVATE_KEY: ${{ secrets.DEV_PRIVATE_KEY }}
          CHAINLINK_NODE_ACCOUNT: ${{ secrets.DEV_CHAINLINK_NODE_ACCOUNT }}
          CHAINLINK_JOB_ID: ${{ secrets.DEV_CHAINLINK_JOB_ID }}
          ALCHEMY_API_KEY: ${{ secrets.DEV_ALCHEMY_API_KEY }}
        run: npm run deploy development
      - name: Deploy for staging environment
        if: ${{ github.ref == 'refs/heads/master' }}
        env:
          PRIVATE_KEY: ${{ secrets.STG_PRIVATE_KEY }}
          CHAINLINK_NODE_ACCOUNT: ${{ secrets.STG_CHAINLINK_NODE_ACCOUNT }}
          CHAINLINK_JOB_ID: ${{ secrets.STG_CHAINLINK_JOB_ID }}
          ALCHEMY_API_KEY: ${{ secrets.STG_ALCHEMY_API_KEY }}
        run: npm run deploy staging
      - run: |
          git add .
      - name: Check diff
        shell: bash
        id: diff
        run: |
          echo "::set-output name=count::$(git diff --staged --name-only . | wc -l)"
      - name: Commit and push
        uses: EndBug/add-and-commit@v9
        if: steps.diff.outputs.count > 0
        with:
          message: 'chore: update deployment files'
          push: true
