name: Open markets

on:
  workflow_dispatch:
    inputs:
      network:
        description: 'Network'
        required: true
        default: 'development'
        type: choice
        options:
          - development
          - development-arb
          - development-ava
          - development-fil
          - staging
          - staging-arb
          - staging-ava
          - staging-fil
          - sepolia
          - mainnet
          - arbitrum-sepolia
          - arbitrum-one
          - avalanche-mainnet
          - polygon-zkevm-mainnet
          - filecoin-mainnet

jobs:
  deploy:
    name: Open markets
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.network }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - name: Install Dependencies
        run: npm ci
      - name: Set environment variables
        run: |
          echo "PRIVATE_KEY=${{ secrets.PRIVATE_KEY }}" >> $GITHUB_ENV
          echo "ALCHEMY_API_KEY=${{ secrets.ALCHEMY_API_KEY }}" >> $GITHUB_ENV
          echo "ANKR_API_KEY=${{ secrets.ANKR_API_KEY }}" >> $GITHUB_ENV
          echo "INFURA_API_KEY=${{ secrets.INFURA_API_KEY }}" >> $GITHUB_ENV
      - name: Build Smart Contracts
        run: npm run compile
      - name: Run task
        shell: bash
        run: npx hardhat open-markets --network ${{ github.event.inputs.network }}
