name: Register orders

on:
  workflow_dispatch:
    inputs:
      network:
        description: 'Network'
        required: true
        default: 'development'
        type: choice
        options:
          - development
          - staging
      collateralCurrency:
        description: 'CollateralCurrency'
        required: true
        default: 'ETH'
        type: choice
        options:
          - ETH
          - USDC
      marketCurrency:
        description: 'MarketCurrency'
        required: true
        default: 'FIL'
        type: choice
        options:
          - FIL
          - ETH
          - USDC
          - BTC
      maturity:
        description: 'Maturity'
        required: true
        type: string
      midUnitPrice:
        description: 'MidUnitPrice'
        required: true
        type: string
      orderAmount:
        description: 'OrderAmount'
        required: true
        type: string
      orderCount:
        description: 'OrderCount'
        required: true
        type: string

jobs:
  deploy:
    name: Register orders
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - name: Install Dependencies
        run: npm ci
      - name: Set env for development environment
        if: ${{ github.event.inputs.network == 'development' }}
        run: |
          echo "PRIVATE_KEY=${{ secrets.DEV_PRIVATE_KEY }}" >> $GITHUB_ENV
          echo "ALCHEMY_API_KEY=${{ secrets.DEV_ALCHEMY_API_KEY }}" >> $GITHUB_ENV
      - name: Set env for staging environment
        if: ${{ github.event.inputs.network == 'staging' }}
        run: |
          echo "NETWORK=staging" >> $GITHUB_ENV
          echo "ALCHEMY_API_KEY=${{ secrets.STG_ALCHEMY_API_KEY }}" >> $GITHUB_ENV
      - name: Build Smart Contracts
        run: npm run compile
      - name: Run task
        shell: bash
        run: >
          npx hardhat register-orders
          --network ${{ github.event.inputs.network }}
          --collateral-currency ${{ github.event.inputs.collateralCurrency }}
          --market-currency ${{ github.event.inputs.marketCurrency }}
          --maturity ${{ github.event.inputs.maturity }}
          --mid-unit-price ${{ github.event.inputs.midUnitPrice }}
          --amount ${{ github.event.inputs.orderAmount }}
          --order-count ${{ github.event.inputs.orderCount }}
