name: Reset smart contracts

on:
  workflow_dispatch:
    inputs:
      network:
        description: 'Network'
        required: true
        default: 'development'
        type: choice
        options:
          - development
          - staging
      compoundFactor:
        description: 'Initial Compound Factor'
        default: '1000000000000000000'
        required: false
        type: string

jobs:
  deploy:
    name: Reset Smart Contracts
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.MACHINE_USER_APP_ID }}
          private_key: ${{ secrets.MACHINE_USER_PRIVATE_KEY }}
      - uses: actions/checkout@v3
        with:
          token: ${{ steps.generate_token.outputs.token }}
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - name: Install Dependencies
        run: npm ci
      - name: Build Smart Contracts
        run: npm run compile
      - name: Deploy for development environment
        if: ${{ github.event.inputs.network == 'development' }}
        env:
          PRIVATE_KEY: ${{ secrets.DEV_PRIVATE_KEY }}
          ALCHEMY_API_KEY: ${{ secrets.DEV_ALCHEMY_API_KEY }}
          INITIAL_COMPOUND_FACTOR: ${{ github.event.inputs.compoundFactor }}
          UNISWAP_SWAP_ROUTER_CONTRACT: ${{ secrets.DEV_UNISWAP_SWAP_ROUTER_CONTRACT }}
        run: npm run deploy:force development
      - name: Deploy for staging environment
        if: ${{ github.event.inputs.network == 'staging' }}
        env:
          PRIVATE_KEY: ${{ secrets.STG_PRIVATE_KEY }}
          ALCHEMY_API_KEY: ${{ secrets.STG_ALCHEMY_API_KEY }}
          INITIAL_COMPOUND_FACTOR: ${{ github.event.inputs.compoundFactor }}
          UNISWAP_SWAP_ROUTER_CONTRACT: ${{ secrets.STG_UNISWAP_SWAP_ROUTER_CONTRACT }}
        run: npm run deploy:force staging
      - name: Commit and push
        shell: bash
        run: |
          git add .
          git config user.name "SF Machine User[bot]"
          git config user.email "${{ secrets.MACHINE_USER_APP_ID }}+sf-machine-user[bot]@users.noreply.github.com"
          git commit -m "chore: reset smart contracts"
          git push
