name: Reset smart contracts

on:
  workflow_dispatch:
    inputs:
      network:
        description: 'Network'
        required: true
        default: 'development'
        type: choice
        options:
          - development
          - staging

jobs:
  deploy:
    name: Reset Smart Contracts
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.network }}
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.MACHINE_USER_APP_ID }}
          private_key: ${{ secrets.MACHINE_USER_PRIVATE_KEY }}
      - uses: actions/checkout@v3
        with:
          token: ${{ steps.generate_token.outputs.token }}
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - name: Install Dependencies
        run: npm ci
      - name: Build Smart Contracts
        run: npm run compile
      - name: Deploy smart contracts
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}
          INITIAL_COMPOUND_FACTOR: ${{ vars.INITIAL_COMPOUND_FACTOR }}
          UNISWAP_SWAP_ROUTER_CONTRACT: ${{ vars.UNISWAP_SWAP_ROUTER_CONTRACT }}
          UNISWAP_SWAP_QUOTER_CONTRACT: ${{ vars.UNISWAP_SWAP_QUOTER_CONTRACT }}
          TOKEN_EFIL: ${{ vars.TOKEN_EFIL }}
          TOKEN_USDC: ${{ vars.TOKEN_USDC }}
          TOKEN_WBTC: ${{ vars.TOKEN_WBTC }}
          TOKEN_WETH: ${{ vars.TOKEN_WETH }}
          FIL_TO_ETH_RATE: ${{ vars.FIL_TO_ETH_RATE }}
          ETH_TO_USD_RATE: ${{ vars.ETH_TO_USD_RATE }}
          BTC_TO_ETH_RATE: ${{ vars.BTC_TO_ETH_RATE }}
          USDC_TO_ETH_RATE: ${{ vars.USDC_TO_ETH_RATE }}
        run: npm run deploy:force ${{ github.event.inputs.network }}
      - name: Commit and push
        shell: bash
        run: |
          git add .
          git config user.name "SF Machine User[bot]"
          git config user.email "${{ secrets.MACHINE_USER_APP_ID }}+sf-machine-user[bot]@users.noreply.github.com"
          git commit -m "chore: reset smart contracts"
          git push
