name: Reset smart contracts

on:
  workflow_dispatch:
    inputs:
      network:
        description: 'Network'
        required: true
        default: 'development'
        type: choice
        options:
          - development
          - staging

jobs:
  deploy:
    name: Reset Smart Contracts
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.network }}
    outputs:
      docgenDiff: ${{ steps.docgenDiff.outputs.count }}
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.MACHINE_USER_APP_ID }}
          private_key: ${{ secrets.MACHINE_USER_PRIVATE_KEY }}
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ (github.event.inputs.network == 'development' && 'develop') || 'main' }}
          token: ${{ steps.generate_token.outputs.token }}
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - name: 'Setup for git'
        run: |
          git config user.name "SF Machine User[bot]"
          git config user.email "${{ secrets.MACHINE_USER_APP_ID }}+sf-machine-user[bot]@users.noreply.github.com"
      - name: Install Dependencies
        run: npm ci
      - name: Build Smart Contracts
        run: npm run compile
      - name: Set environment variables
        run: |
          echo "INITIAL_COMPOUND_FACTOR=${{ vars.INITIAL_COMPOUND_FACTOR }}" >> $GITHUB_ENV
          echo "INITIAL_MARKET_OPENING_DATE=${{ vars.INITIAL_MARKET_OPENING_DATE }}" >> $GITHUB_ENV
          echo "INITIAL_MARKET_PRE_OPENING_DATE=${{ vars.INITIAL_MARKET_PRE_OPENING_DATE }}" >> $GITHUB_ENV
          echo "INITIAL_MARKET_COUNT=${{ vars.INITIAL_MARKET_COUNT }}" >> $GITHUB_ENV
          echo "TOTAL_MARKET_COUNT=${{ vars.TOTAL_MARKET_COUNT }}" >> $GITHUB_ENV
          echo "OPENING_DATE_INTERVAL=${{ vars.OPENING_DATE_INTERVAL }}" >> $GITHUB_ENV
          echo "MARKET_BASE_PERIOD=${{ vars.MARKET_BASE_PERIOD }}" >> $GITHUB_ENV
          echo "ENABLE_AUTO_UPDATE=true" >> $GITHUB_ENV
          echo "NATIVE_CURRENCY_SYMBOL=${{ vars.NATIVE_CURRENCY_SYMBOL }}" >> $GITHUB_ENV
          echo "NATIVE_TOKEN_ADDRESS=${{ vars.NATIVE_TOKEN_ADDRESS }}" >> $GITHUB_ENV
          echo "NATIVE_TOKEN_SYMBOL=${{ vars.NATIVE_TOKEN_SYMBOL }}" >> $GITHUB_ENV
          echo "TOKEN_WFIL=${{ vars.TOKEN_WFIL }}" >> $GITHUB_ENV
          echo "TOKEN_USDC=${{ vars.TOKEN_USDC }}" >> $GITHUB_ENV
          echo "TOKEN_WBTC=${{ vars.TOKEN_WBTC }}" >> $GITHUB_ENV
          echo "TOKEN_WETH=${{ vars.TOKEN_WETH }}" >> $GITHUB_ENV
          echo "PRICE_FEED_ADDRESSES_WFIL=${{ vars.PRICE_FEED_ADDRESSES_WFIL }}" >> $GITHUB_ENV
          echo "PRICE_FEED_ADDRESSES_USDC=${{ vars.PRICE_FEED_ADDRESSES_USDC }}" >> $GITHUB_ENV
          echo "PRICE_FEED_ADDRESSES_WBTC=${{ vars.PRICE_FEED_ADDRESSES_WBTC }}" >> $GITHUB_ENV
          echo "PRICE_FEED_ADDRESSES_WETH=${{ vars.PRICE_FEED_ADDRESSES_WETH }}" >> $GITHUB_ENV
          echo "PRICE_FEED_MAX_HEARTBEAT_WFIL=${{ vars.PRICE_FEED_MAX_HEARTBEAT_WFIL }}" >> $GITHUB_ENV
          echo "PRICE_FEED_MAX_HEARTBEAT_USDC=${{ vars.PRICE_FEED_MAX_HEARTBEAT_USDC }}" >> $GITHUB_ENV
          echo "PRICE_FEED_MAX_HEARTBEAT_WBTC=${{ vars.PRICE_FEED_MAX_HEARTBEAT_WBTC }}" >> $GITHUB_ENV
          echo "PRICE_FEED_MAX_HEARTBEAT_WETH=${{ vars.PRICE_FEED_MAX_HEARTBEAT_WETH }}" >> $GITHUB_ENV
          echo "PRICE_FEED_MOCK_RATE_WFIL_TO_ETH=${{ vars.PRICE_FEED_MOCK_RATE_WFIL_TO_ETH }}" >> $GITHUB_ENV
          echo "PRICE_FEED_MOCK_RATE_USDC_TO_USD=${{ vars.PRICE_FEED_MOCK_RATE_USDC_TO_USD }}" >> $GITHUB_ENV
          echo "PRICE_FEED_MOCK_RATE_WBTC_TO_BTC=${{ vars.PRICE_FEED_MOCK_RATE_WBTC_TO_BTC }}" >> $GITHUB_ENV
          echo "PRICE_FEED_MOCK_RATE_BTC_TO_USD=${{ vars.PRICE_FEED_MOCK_RATE_BTC_TO_USD }}" >> $GITHUB_ENV
          echo "PRICE_FEED_MOCK_RATE_ETH_TO_USD=${{ vars.PRICE_FEED_MOCK_RATE_ETH_TO_USD }}" >> $GITHUB_ENV
          echo "PRIVATE_KEY=${{ secrets.PRIVATE_KEY }}" >> $GITHUB_ENV
          echo "ALCHEMY_API_KEY=${{ secrets.ALCHEMY_API_KEY }}" >> $GITHUB_ENV
          echo "ENABLE_FAUCET=true" >> $GITHUB_ENV
      - name: Deploy smart contracts
        run: npm run deploy:force ${{ github.event.inputs.network }}
      - name: Commit and push
        shell: bash
        run: |
          git add .
          git commit -m "chore: reset smart contracts" --no-verify
          git push
      - name: Update documents
        if: ${{ github.event.inputs.network == 'development' }}
        run: |
          npm run docgen
          git add .
      - name: Check diff
        shell: bash
        id: docgenDiff
        run: |
          echo "count=$(git diff --staged --name-only . | wc -l)" >> $GITHUB_OUTPUT
      - name: Commit and push
        shell: bash
        if: ${{ steps.docgenDiff.outputs.count > 0 }}
        run: |
          git commit -m "chore: update docs" --no-verify
          git push
      - name: Merge main into develop
        shell: bash
        if: ${{ github.event.inputs.network != 'development' }}
        run: |
          git switch develop
          git merge main --no-verify
          git push
